
server:
  port: 8118

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cm_system?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 1q2w3e4r
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  redis:
    port: 6379
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 8
      shutdown-timeout: 100ms

# spring.redis.password=123456
# spring.redis.database=1
# spring.redis.cluster.max-redirects=3
# spring.redis.cluster.nodes=192.168.1.64:7006,192.168.1.64:7005,192.168.1.64:7004,192.168.1.64:7003,192.168.1.64:7002,192.168.1.64:7001

mybatis-plus:
  type-enums-package: com.excelsecu.cmsystem.common.enums
  global-config:
    db-config:
      logic-delete-field: flag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true  # 启用驼峰命名

password:
  algorithmName: md5
  hashIterations: 2
